name: ".reusable-deploy"

on:
  workflow_call:
    inputs:
      ENVIRONMENT_STAGE_NAME:
        required: true
        type: string
      ANSIBLE_PROJECT_PATH:
        required: true
        type: string
      CURRENT_PROJECT_PATH:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
      RUNNER_LABELS:
        required: true
        type: string[]

jobs:
  deploy:
    name: "Deploy ${{ inputs.ENVIRONMENT_STAGE_NAME }}"
    environment: ${{ inputs.ENVIRONMENT_STAGE_NAME }}
    runs-on: ${{ inputs.RUNNER_LABELS }}
    steps:
      - name: "Resolve dropfolder path"
        run: |
          echo "dropfolder_path=${{ inputs.ANSIBLE_PROJECT_PATH }}/_dropfolder/${{ inputs.PROJECT_NAME }}" >> $GITHUB_ENV

      - name: "Resolve artifact path"
        run: |
          echo "artifact_path=${GITHUB_WORKSPACE}/${{ inputs.ARTIFACT_NAME }}" >> $GITHUB_ENV

      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ARTIFACT_NAME }}

      - name: "Extract artifact"
        run: |
          sudo rm -rf ${{ env.dropfolder_path }}/*
          sudo mkdir -p ${{ env.dropfolder_path }}
          sudo chmod 0755 ${{ env.dropfolder_path }}
          sudo tar -xzf "${{ env.artifact_path }}" -C "${{ env.dropfolder_path }}"

      - name: "Run Ansible Playbook"
        run: |
          cd ${{ inputs.ANSIBLE_PROJECT_PATH }}
          ansible-playbook ./playbooks/deploy-docker.yml \
            -i "${{ inputs.ANSIBLE_PROJECT_PATH }}/inventory/hosts.ini" \
            -e "ANSIBLE_PROJECT_PATH=${{ inputs.ANSIBLE_PROJECT_PATH }}" \
            -e "CURRENT_PROJECT_PATH=${{ inputs.CURRENT_PROJECT_PATH }}" \
            -e "DROPFOLDER_PATH=${{ env.dropfolder_path }}"
