name: "Deploy Cloudflared"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: true
        default: "Manual trigger"

env:
  ANSIBLE_PROJECT: "${{ vars.ANSIBLE_PROJECT }}"
  CLOUDFLARED_PROJECT: "${{ vars.CLOUDFLARED_PROJECT }}"

jobs:
  deploy-cloudflared:
    name: "Deploy Cloudflared"
    runs-on:
      - "self-hosted"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Copy project to dropfolder"
        run: |
          sudo rm -rf ${ANSIBLE_PROJECT}/_dropfolder/cloudflared/*
          sudo mkdir -p ${ANSIBLE_PROJECT}/_dropfolder/cloudflared
          sudo chmod 0755 ${ANSIBLE_PROJECT}/_dropfolder/cloudflared
          sudo cp -r ./docker/* ${ANSIBLE_PROJECT}/_dropfolder/cloudflared/
      - name: "Run Ansible Playbook"
        run: |
          cd ${ANSIBLE_PROJECT}
          ansible-playbook ./ansible/playbooks/deploy-cloudflared.yml \
            -i ${ANSIBLE_PROJECT}/inventory/hosts.ini \
            -e ANSIBLE_PROJECT=${ANSIBLE_PROJECT} \
            -e CLOUDFLARED_PROJECT=${CLOUDFLARED_PROJECT}
