name: "pipeline"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: true
        default: "Manual trigger"

jobs:

  build:
    name: "Build"
    uses: "panoramicovphc/reusable-workflows/.github/workflows/.reusable-build.yml@v1"

  deploy-dev:
    uses: "./.github/workflows/.reusable-deploy.yml"
    needs: [ build ]
    with:
      ENVIRONMENT_STAGE_NAME: "dev"
      ENVIRONMENT_STAGE_LABEL: "development"
      ANSIBLE_PROJECT_PATH: "${{ vars.ANSIBLE_PROJECT_PATH }}"
      CURRENT_PROJECT_PATH: "${{ vars.CURRENT_PROJECT_PATH }}"
      PROJECT_NAME: "cloudflared"
      ARTIFACT_NAME: "${{ needs.build.outputs.ARTIFACT_NAME }}"
